# Generated by Django 4.1.1 on 2022-09-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_features_delete_feature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
    ]
